export const LOADER_ACTIVE = "LOADER_ACTIVE";
export const LOADER_STOP = "LOADER_STOP";

export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";

export const GET_IMAGES_SUCCESS = "GET_IMAGES_SUCCESS";
export const GET_IMAGES_ERROR = "GET_IMAGES_ERROR";

export const GET_BOOKING_SUCCESS = "GET_RESERVES_SUCCESS";
export const GET_BOOKING_ERROR = "GET_RESERVES_ERROR";

export const UPDATE_BOOKING = "UPDATE_BOOKING";
export const POST_BOOKING_SUCCESS = "POST_RESERVES_SUCCESS";
export const POST_BOOKING_ERROR = "POST_RESERVES_ERROR";
