export const LOADER_ACTIVE = "LOADER_ACTIVE";
export const LOADER_STOP = "LOADER_STOP";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export const GET_IMAGES_SUCCESS = "GET_IMAGES_SUCCESS";
export const GET_IMAGES_ERROR = "GET_IMAGES_ERROR";
